Downgrade logstash-logback-encoder
To avoid:

java.lang.NoSuchMethodError: 'java.time.Instant ch.qos.logback.classic.spi.ILoggingEvent.getInstant()'

7.4 requires logback >= 1.3 apparently, which is presumably bundled
in Play somewhere.